#!/bin/bash

# Author: Saurav Kumar
# Version: 1.0

### KivyConnectServer Installation Notes ###
#   1. Creating python based virtual environment.
#   2. Installing all the required packages needed by kivyConnectServer.
#   3. Setting up systemd settings for kivyConnectServer.
#   4. Starting kivyConnectServer and enabling it so that it starts automatically when system reboots.
#   5. Thinking of smiling face of user installing kivyConnectServer.

INSDIR=~/.kivyConnect
cp -Rp . $INSDIR  # copy all files of current directory to user home install directory
mkdir -p $INSDIR/logs  # creating the logs directory
sudo apt-get install python-dev virtualenv python-pip  # installing global packages
virtualenv $INSDIR/venvserver  # creating virtualenv for server
$INSDIR/venvserver/bin/pip install -r requirements_server.txt  # install all required packages inside virtualenv
sed -i "s/@USER/$USER/g; s/@DISPLAY/$DISPLAY/g" $INSDIR/systemd_kivyconnectserver.conf $INSDIR/kivyserver.ini  # changes @ variables to actual environment variables
sudo cp $INSDIR/systemd_kivyconnectserver.conf /etc/systemd/system/kivyconnectserver.service  # enabling sys start run
sudo systemctl daemon-reload
sudo systemctl start kivyconnectserver
sudo systemctl enable kivyconnectserver
sudo service kivyconnectserver restart
